# Build stage
FROM node:18-alpine AS build
WORKDIR /app

COPY client/package*.json ./
RUN npm install

COPY client/ .

# build arg
ARG VITE_API_URL
ENV VITE_API_URL=$VITE_API_URL

RUN npm run build

# Runtime stage
FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]